### PR TITLE
BUG: Fix Issue #410: Update colorbar_params arguments in overlay_prediction_mask function

### PR DESCRIPTION
**Pull request by Srijay-lab**
The solution suggested by user '[pcscp](https://github.com/pcscp)' appears working, I incorporated the same.

### CODE REVIEW

**Comment by shaneahmed** [comment]
@Srijay-lab Please can you add the updated jupyter notebook as well after applying this fix?

**Comment by Srijay-lab** [comment]
> @Srijay-lab Please can you add the updated jupyter notebook as well after applying this fix?

@shaneahmed There was no change in the Juputer notebook. It's working fine now. I applied fix inside the library function.

**Review by shaneahmed — APPROVED** [review]
Thanks @Srijay-lab

**Comment by DavidBAEpstein** [comment]
What was the bug?
Did it require any change in the packages required for the tiatoolbox environment?
I am now investigating whether there is still a bug in "overlay_prediction_mask".

**Pull request merged**
