### PR TITLE
🐍 Update Supported Python Versions (add 3.11 )

### PR DESCRIPTION
**Pull request by John-P**
- [x] Add 3.11 to the GitHub Actions CI workflow.
- [x] Add 3.11 to setup.py
- [x] Update pip install workflow.
- [x] Update conda requirements python versions.

Waiting on some dependencies to update:

- [x] Shapely (closed) https://github.com/shapely/shapely/issues/1584
  - PyGeos https://github.com/pygeos/pygeos/issues/457
- [x] PyTorch https://github.com/pytorch/pytorch/issues/86566 
    - [x] PyTorch 2.0 supports Python 3.11 
    - [ ] `torch.compile` is not fully supported yet.
- [x] Scipy 1.9.2 not supported by Scikit-image https://github.com/scikit-image/scikit-image/pull/6773
- [x] numba https://github.com/numba/numba/issues/8304 support https://github.com/numba/numba/milestone/63
  - [x] https://github.com/numba/numba/issues/8841
- [x] OpenSlide support for Python 3.11 https://github.com/openslide/openslide-python/issues/189 
  - [ ] https://github.com/openslide/openslide-python/pull/188

### CODE REVIEW

**Comment by John-P** [comment]
Shapely does not yet support 3.11 (https://pypi.org/project/shapely/)

**Comment by shaneahmed** [comment]
> Shapely does not yet support 3.11 (https://pypi.org/project/shapely/)

Let's keep this PR as draft until we get all the dependencies supporting 3.11

**Comment by Erotemic** [comment]
Shapely does have 311 wheels now. Still waiting on pygeos.

**Comment by shaneahmed** [comment]
> Shapely does have 311 wheels now. Still waiting on pygeos.

Great! I will update this now.

**Comment by shaneahmed** [comment]
PyTorch does not support Python 3.11 yet

https://github.com/pytorch/pytorch/issues/86566

**Comment by Somiona** [comment]
Pytorch launched version 2.0.0 and officially support python3.11 now

**Pull request merged**
