### PR TITLE
[skip travis] EG: add example notebook on advanced model techniques

### PR DESCRIPTION
**Pull request by mostafajahanifar**
Adding a new example notebook on semantic segmentation (more generally, model prediction) task where advanced topics are addressed. Particularly, in this notebook we are trying to demonestrate how user can use Tiatoolbox to solve the problems in the following three scenarios:

- [x] 1. Instead of pretrained models embedded in Tiatoolbox's repsitory, user wants to use your own deep learning model (in Pytorch) in the Tiatoolbox prediction workflow.

- [x] 2. User's input data is of an exotic form which the Tiatoolbox data stream functionality does not support by default.

### CODE REVIEW

**Comment by vqdang** [comment]
<p>In the example bolow &gt; In the example below</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/174/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mostafajahanifar** [comment]
<p>I added "# your code here" expression but kept the pass as well, because when there is no code, they should have the "pass" statement at the end.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/174/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mostafajahanifar** [comment]
<p>Sure, dear flake-8 :-p</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/174/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mostafajahanifar** [comment]
<p>xreader is a function, on the other hand, XReader is class that uses xreader function.</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/174/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by shaneahmed — APPROVED** [review]

**Pull request merged**
