### PR TITLE
DOC: JNB-RTD consistency for idars.ipynb

### PR DESCRIPTION
**Pull request by DavidBAEpstein**
- MAINT: catch up with another branch
- BUG: fix on Macos without GPU by WORKERS=0
- DOC; change comment about ON_GPU
- DOC: Run on Colab with GPU and ON_GPU--True. Save with output.

### CODE REVIEW

**Review by mostafajahanifar — CHANGES_REQUESTED** [review]
Thanks David for the upgrading this notebook. 

The only minor comment from me that requires attention is fixing the legend for the tumour prediction figure, where both tumour and non-tumour have the same colour.

**Comment by DavidBAEpstein** [comment]
<p>I might be able to guess how to fix this, and will have a try</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/421/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by DavidBAEpstein** [comment]
<p>My "rix" above with defining WORKERS does not succeed with 07-advanced-modeling.ipynb.. I get an error saying that Cuda-enabled GPU is needed. I don't understand what is going on, but I think the code requires a version of torch that requires GPU.</p><p> </p><p>So I am on the point of removing all mention of ON_GPU from this notebook, since this implies, incorrectly, that a version not using GPU will run successfully (as.it does in the case of idars.ipynb)</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/421/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by DavidBAEpstein** [comment]
<p>I changed non-tumour colour to green. The overlay image changed dramatically, in the way I expected. The legend </p><p>remained red throughout. My guess is that this is related to the warning message immediately above the image, namely</p><p>|2022-07-20|15:37:40.408| [WARNING] ....</p><p>Perhaps overlay_prediction_mask cannot cope with scale &gt; 1, and the scale for the legend is incorrect.</p><p>The code in the develop version is identical with the code here, and it gives a correct legend. So I think the behaviour is not properly controlled by overlay_prediction_mask, so that the same code gives very different results under very very slightly different conditions.</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/421/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by DavidBAEpstein** [comment]
inference-pipelines/idars.ipynb runs successfully under Macos without GPU (ON_GPU == False)
In order for it to run correctly under Colab with GPU (ON_GPU == True) it was necessary to replace "pip install tiatoolbox" with
"pip install git+https://github.com/TissueImageAnalytics/tiatoolbox.git@develop" in order to use @Srijay-lab's fix of overlay-prediction-mask". This will need to be changed back at the next release of tiatoolbox.

**Comment by DavidBAEpstein** [comment]
> Thanks David for the upgrading this notebook.
> 
> The only minor comment from me that requires attention is fixing the legend for the tumour prediction figure, where both tumour and non-tumour have the same colour.

The error was due to a bug in the function `overlay_prediction_mask`, which is fixed in the latest version of develop.

**Comment by DavidBAEpstein** [comment]
@mostafajahanifar @shaneahmed This PR is now ready for review. I was able to save it with output, since the code cells have not been significantly changed since it was last run on a TIA Centre machine with GPU (not by me).

**Review by shaneahmed — APPROVED** [review]
Thanks @DavidBAEpstein for your work on this.
Looks good!
I have added hidden cells as they create redundant text in the documentation. The sections and subsections look fine to me after removing these cells from readthedocs.

**Pull request merged**
