### PR TITLE
DEV: Add macOS To pip Install Workflow

### PR DESCRIPTION
**Pull request by John-P**
This PR adds macOS pip install test cases to the GitHub workflow.

### CODE REVIEW

**Comment by shaneahmed** [comment]
Please can you add the workflow for checking requirements file as well?
As this will fail once I use requirements.txt in setup.py

**Comment by John-P** [comment]
> Please can you add the workflow for checking requirements file as well?
As this will fail once I use requirements.txt in setup.py

Sorry, I'm not sure what this means. I don't know what requirements check you need here. I cannot see a reason why this would fail when using requirements.txt in setup.py.

**Comment by shaneahmed** [comment]
> > Please can you add the workflow for checking requirements file as well?
> > As this will fail once I use requirements.txt in setup.py
> 
> Sorry, I'm not sure what this means. I don't know what requirements check you need here. I cannot see a reason why this would fail when using requirements.txt in setup.py.

Please check this workflow https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/.github/workflows/conda-env-create.yml. This requires copying the requirements file to temp directory. This doesn't work on MacOS.

**Comment by John-P** [comment]
> Please check this workflow https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/.github/workflows/conda-env-create.yml. This requires copying the requirements file to temp directory. This doesn't work on MacOS.

The linked workflow is using a different install process (anaconda). This workflow is just using pip and does not need a tmp directory.

**Comment by John-P** [comment]
@shaneahmed Looks like setup.py doesn't like the commands beginning with "--". Could potentially try simply filtering out those lines.

**Review by shaneahmed — APPROVED** [review]
Thanks @John-P

**Pull request merged**
