### PR TITLE
[skip travis] EG: Add Example Multi-Task Segmentor Notebook

### PR DESCRIPTION
**Pull request by adamshephard**
- Add example notebook for the multi-task segmentor.

### CODE REVIEW

**Comment by John-P** [comment]
@adamshephard, do you need Travis to run for this PR? If not, can youadd `[skip travis]` to the PR title please.

**Review by DavidBAEpstein — CHANGES_REQUESTED** [review]
@adamshephard  [Multi.docx](https://github.com/TissueImageAnalytics/tiatoolbox/files/7741700/Multi.docx)
Please use Word's Track Changes (TRK mode) to find my suggestions for changes. If you use "Next", you will not miss the occasional isolated comma that I think is needed.
I haven't looked at this PR's version of Examples/README.md. I need help in locating it. There was a version of this README by Mostafa.I'm not sure how ReviewNB is displaying diffs between this PR's version and Mostafa's version, but would like to see the differences in context before commenting. I have not been able to access the png file (because the relevant branch doesn't exist for me), so I don't know how that fits in to this PR. Possibly the png file is an improvement that is unrelated to the other material, but there's no way for me to tell.

**Comment by adamshephard** [comment]
<p>I've kept them seperate so you can make out the different nuclei etc in the images. If they were smaller it would be difficult to visualise.</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adamshephard** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adamshephard** [comment]
<p>Added legend</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adamshephard** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adamshephard** [comment]
<p>Changed slightly and added links</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by adamshephard** [comment]
<p>Added to</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
