### PR TITLE
API: Change `models.controller` API to `models.engine`

### PR DESCRIPTION
**Pull request by Srijay-lab**
- Change `models.controller` API to `models.engine`

### CODE REVIEW

**Review by shaneahmed — COMMENTED** [review]
How about notebooks?

**Comment by Srijay-lab** [comment]
@shaneahmed Just altered the semantic segmentation example notebook and also fixed one minor bug I encountered while testing the notebook.

**Comment by Srijay-lab** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/TissueImageAnalytics/tiatoolbox/pull/185/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by shaneahmed — APPROVED** [review]
Thanks @Srijay-lab 
Looks good to me. Please make the change in the notebook as I mentioned.

**Pull request merged**
